ARG IMAGE_UNDER_TEST
FROM ${IMAGE_UNDER_TEST}

ARG GOSS_VERSION

RUN curl -f -L -v "https://github.com/aelsabbahy/goss/releases/download/${GOSS_VERSION}/goss-linux-amd64" -o /usr/local/bin/goss && \
    chmod +rx /usr/local/bin/goss

RUN mv /start-server.sh /run-server.sh

COPY ./goss.yaml /goss.yaml
COPY ./test-server.sh /start-server.sh

ENV TEST=1

RUN chmod a+x /start-server.sh